version: '3.8'
services:
    mariadb:
        image: mariadb:10.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: toxicology-test
        # volumes:
        #     - './db:/var/lib/mysql'
